#PCD SNOMED Release Parameters

[Setup]
test_mode       = true           #Must be lower case - true or false, test mode will output files to a test folder and make no changes to the live databases
full_name       = 'Name Surname'    #Your full name, in format 'Forename Surname', for signing off emails

#-------------------------------------------------------------------------------------------------------------------

[Dates]
MmmYY           = 'MmmYY'       #The date of the code release database, in format MmmYY
UKreleaseDate   = 'YYYYMMDD'    #UK Monolith release date, in format YYYYMMDD
PrevUKrelDate   = 'YYYYMMDD'    #UK Monolith release date used for the previous release, in format YYYYMMDD  

PCDreleaseDate  = 'YYYYMMDD'    #Date of your upcoming PCD code release publication, in format YYYYMMDD
PrevPCDrelDate  = 'YYYYMMDD'    #Date of the previous PCD code release publication, in format YYYYMMDD

#-------------------------------------------------------------------------------------------------------------------

[Filepaths]
#all outputs will be saved into an outputs folder created in the repo location, and then moved into the following locations at the end of the process.
#If you don't want these to be moved, leave these blank. NOTE: If just one is left blank, no outputs will be moved.

SNOMED_CT            = "insert_folderpath"       #location for SnomedCT_UKPrimaryCareRF2_PRODUCTION_YYYYMMDDT000000Z folder
Publication_Outputs  = "insert_folderpath"       #location for publication folder (relVersion_dd.mm.yy)
PowerBI_xlsx_Outputs = "insert_folderpath"       #location of PowerBI tables
PowerBI_txt_Outputs  = "insert_folderpath"       #location of PowerBI text files and zip

rel_version     = '000'         #the next PCD release number, in the format '000' (can be found sequentially, here: root/001_Publishing_TRUD_Release_SQL)

#-------------------------------------------------------------------------------------------------------------------

[SnomedCT_Folders_Creation]
#export_tables
csv_name        = "insert_filename_with_extension" #name of csv in templates_and_inputs folder to create SnomedCT_UKPrimaryCareRF2_PRODUCTION_YYYYMMDDT000000Z folder structure
folder_count    = 23                                #the number of folders we should see under the SnomedCT_UKPrimaryCareRF2_PRODUCTION_YYYYMMDDT000000Z folder (not inclusive)

#-------------------------------------------------------------------------------------------------------------------

[SQL_table_prefix]
IA_SCT_Chosen   = true          #Have already imported the full UK release?, true/false (If yes, true. If no, false)
IA_input        = 'IA0'         #What is your impact analysis prefix? e.g.: "IA0". Only make change if above=false.

#-------------------------------------------------------------------------------------------------------------------

[Documents]
#UK NHS Primary Care data extraction reference sets word document
additional_info = """ """    #additional information to be included in the extraction reference sets document. If nothing, please leave as an empty string.
team_address    = "insert_address"
team_phone_tel  = "insert_tel"
business_name   =  'NHS England'

#TRUD_pack_req_doc word document: contacts
reciever_email  = "insert_email_address"
team_email      = "insert_email_address"

#-------------------------------------------------------------------------------------------------------------------

[Checking_lists]
accepted_diff_non_ascii = ['é', 'ö', 'ü', 'Å', 'ë', 'å', 'è', 'ç', 'à', 'ā', '–']

#-------------------------------------------------------------------------------------------------------------------

[PowerBI]
Other_services = 1 # number of services classed as 'Other' (as determined in the Rulesets mapping tables)
Confluence_guidance = "the 'Update the Ruleset_published Table' section of https://nhsd-confluence.digital.nhs.uk/pages/viewpage.action?spaceKey=KH&title=Ruleset+Publication+Table+-+Publishing+Business+Rules"

#-------------------------------------------------------------------------------------------------------------------

[Expanded_cluster_lists_Service-level]
ecc_service_list = ['QOF', 'INLIQ', 'NCD']

#-------------------------------------------------------------------------------------------------------------------
[Autogenerated_Emails] #the email body will be generated in the code. If you want to make changes to this, please find in the code, or change the create .eml file before sending.

## Email to xxx team, attached with GDPPR/GPData zip
Email_1.subject = "GDPPR and GPData Reference data"
Email_1.To      = "insert_email_addresses"
Email_1.Cc      = "insert_email_addresses"
# please note, anything in the body surrounded by <> will automatically be populated in the code.
Email_1.body    = """
Hello all,

Please find attached a zip file containing 'GDPPR_<GDPPR_GPdata_fl>' and 'GPData_<GDPPR_GPdata_fl>' following our latest primary care SNOMED refset release.

Kind regards,
<Name>
"""

## Email for PCD refset release with TRUD file, attached with GDPPR/GPData zip
Email_2.subject = "Upcoming publication sprint - PCD refset release and TRUD files"
Email_2.To      = "insert_email_addresses"
Email_2.Cc      = "insert_email_addresses"
# please note, anything in the body surrounded by <> will automatically be populated in the code.
Email_2.body    = """
Hello,

Please can you add this into an upcoming publication sprint? We have given a release date of <Target_TRUD_Date>; however, if this does not fit into a sprint easily, it can be later.

Kind regards,
<Name>
"""

## Email for GDPPR / COVID-19 at risk cluster content changes, attached with c19_changes xlsx
Email_3.subject = "GDPPR / COVID-19 at risk cluster content changes - PCD refset release" #Please note: the release verion and date will be added to the end of this in the code
Email_3.To      = "insert_email_addresses"
Email_3.Cc      = "insert_email_addresses"
# please note, anything in the body surrounded by <> will automatically be populated in the code.
Email_3.body    = """
Hello all,

Please find attached a summary of changes to the clusters which affect the C19 at risk patients extract and the GDPPR extract, following the above mentioned PCD SNOMED release.

These changes should be implemented by suppliers within 8 weeks of the release date and so may affect the patients appearing within these extract between now and 12 weeks time.

Kind regards,
<Name>
"""

## Email for PCD SNOMED Release Suppliers, no attachments
Email_4.subject = "PCD SNOMED Release Suppliers Sharepoint"
Email_4.To      = "insert_email_addresses"
Email_4.Cc      = "insert_email_addresses"
# please note, anything in the body surrounded by <> will automatically be populated in the code.
Email_4.body    = """
Hello,

I have now uploaded the zip file to the suppliers sharepoint. Can you please let them know that the latest Primary Care SNOMED Code Release pack <rel_version> is now available?

Many thanks,
<Name>
"""

## Email for updating PCD Reference Portal, insert image
Email_5.subject = 'PCD Reference Set Portal Webpage Update'
Email_5.To      = "insert_email_addresses"
Email_5.Cc      = "insert_email_addresses"
# please note, this text is written in HTML - THIS IS NECESSARY TO INCLUDE AN IMAGE
Email_5.body    = """
Hello Team,

Please can you replace one of the files on one of our webpages?  The web page is https://digital.nhs.uk/data-and-information/data-collections-and-data-sets/data-collections/quality-and-outcomes-framework-qof/quality-and-outcome-framework-qof-business-rules/primary-care-domain-reference-set-portal 
We would like the attached file to replace the one currently returned when a user clicks on the ‘Download the data files’ option illustrated below: 
<img>

Should you have any questions or if anything is unclear please let me know and I will be happy to clarify/talk it through.

Best regards, 
<Name>
"""
Email_5.image_embed = "./templates_and_inputs/web_replace.jpg"


## Email for DGAT, ECL changes for published or business rules in development
Email_6.subject     = 'PCD SNOMED Release / Changes to Rulesets and Services ECCs'
Email_6.To          = "insert_email_addresses"
Email_6.Addressee   = 'both '
Email_6.Cc          = "insert_email_addresses"
Email_6.body        = """ """

#-------------------------------------------------------------------------------------------------------------------

[Connection]
SQL_Server      = "insert_server_name"
#-------------------------------------------------------------------------------------------------------------------

[LiveDatabases] 
#databases to use in live mode

UKSNOMEDCT.prior_db         = "update_here"
UKSNOMEDCT.db               = "update_here"
UKSNOMEDCT.SCT_CONCEPT      = "update_here"
UKSNOMEDCT.SCT_DESCRIPTION  = "update_here"
UKSNOMEDCT.SCT_REFSET       = "update_here"

LocalSNOMEDCT.db                = "update_here"
LocalSNOMEDCT.Concept           = "update_here"
LocalSNOMEDCT.Refsets           = "update_here"
LocalSNOMEDCT.ModuleDependency  = "update_here"
LocalSNOMEDCT.TRUD_ID_Generator = "update_here"
LocalSNOMEDCT.Description       = "update_here"
LocalSNOMEDCT.Relationship      = "update_here"
LocalSNOMEDCT.OwlExpression     = "update_here"
LocalSNOMEDCT.Language          = "update_here"
LocalSNOMEDCT.RefsetDescriptor  = "update_here"
LocalSNOMEDCT.PrevRefsetSnapshot = "update_here"

ClusterManagement.db                        = "update_here"
ClusterManagement.Clusters                  = "update_here"
ClusterManagement.Cluster_Ruleset           = "update_here"
ClusterManagement.Cluster_Output            = "update_here"
ClusterManagement.Cluster_Population        = "update_here"
ClusterManagement.Rulesets                  = "update_here"
ClusterManagement.Ruleset_Published         = "update_here"
ClusterManagement.Outputs                   = "update_here"
ClusterManagement.Output_Ruleset            = "update_here"
ClusterManagement.Output_Population         = "update_here"
ClusterManagement.Populations               = "update_here"
ClusterManagement.Population_Ruleset        = "update_here"
ClusterManagement.Code_Decision_Log_Archive = "update_here"


#-------------------------------------------------------------------------------------------------------------------

[TestDatabases] 
#databases to use in test mode

UKSNOMEDCT.prior_db         = "update_here"
UKSNOMEDCT.db               = "update_here"
UKSNOMEDCT.SCT_CONCEPT      = "update_here"
UKSNOMEDCT.SCT_DESCRIPTION  = "update_here"
UKSNOMEDCT.SCT_REFSET       = "update_here"

LocalSNOMEDCT.db                = "update_here"
LocalSNOMEDCT.Concept           = "update_here"
LocalSNOMEDCT.Refsets           = "update_here"
LocalSNOMEDCT.ModuleDependency  = "update_here"
LocalSNOMEDCT.TRUD_ID_Generator = "update_here"
LocalSNOMEDCT.Description       = "update_here"
LocalSNOMEDCT.Relationship      = "update_here"
LocalSNOMEDCT.OwlExpression     = "update_here"
LocalSNOMEDCT.Language          = "update_here"
LocalSNOMEDCT.RefsetDescriptor  = "update_here"
LocalSNOMEDCT.PrevRefsetSnapshot = "update_here"